### ISSUE TITLE
Build error using esl edown

### ISSUE THREAD

**Issue by andrakis** [klajo/eunit_addons#2]
Hello,

I'm getting a compile error trying to build `eunit_addons`. It's actually `edown` that's failing to compile.
I'm running on Erlang/OTP R18.

```
==> edown (compile)
deps/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen
deps/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen
Compiling deps/edown/src/edown_doclet.erl failed
```

Looking at the dependency in `rebar.config`, it's pointing to the [esl/edown](https://github.com/esl/edown) repository. This one seems to be very out of date. One of the open issues mentions that the latest master should fix the issue, but it does not.

However, the `esl` version of `edown` is several months behind the version it was originally forked from; ie, the [original edown repo](https://github.com/uwiger/edown) has been updated, but esl's has not.

The fix for me was to adjust the dependency's path to `edown` as such:
```{edown, ".*", {git, "git://github.com/uwiger/edown.git", {tag,"0.4"}}}```

(Side note that I couldn't get rebar to check out the new path, so I manually updated origin for the `deps/edown/.git/config` to `uwiger`'s, did a `git fetch` and then a `git reset --hard origin/master`. I was then able to build `eunit_addons` correctly.)

**Comment by klajo** [comment]
Thanks for the report.  I'll fix it within a couple of days.

Just out of curiosity: Were you using this through mockgyver or directly?

**Comment by andrakis** [comment]
Thank you.

I'm using this directly for the most part, mainly the `?WITH_SETUP` macro.

I sometimes use mockgyver, but mostly I'm using standard eunit practices.

**Comment by klajo** [comment]
Hi,

I've pushed a new version. Hope that works for you.

Cheers,
Klas

**Comment by andrakis** [comment]
Thank you, that commit fixes the issue.

Thanks for your quick response!

**Comment by klajo** [comment]
Excellent. Great to hear that someone puts eunit_addons to use standalone (from mockgyver). :-)
